version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run:
          name: prepare 
          command: apt-get update && apt-get install wget
      - run:
          name: GET Dockerfile 
          command: wget https://raw.githubusercontent.com/minepicco/speechtotext-dockerfile/master/Dockerfile -O Dockerfile
      - run:
          name: Build
          command: docker build . --file Dockerfile --tag minepicco/speechtotext:latest

