version: 2
jobs:
  build:
    docker:
      - image: $circleciimage
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: GET Dockerfile 
          command: wget https://raw.githubusercontent.com/minepicco/speechtotext-dockerfile/master/Dockerfile -O Dockerfile
      - run:
          name: docker ps
          command: docker ps -a
      - run:
          name: build
          command: docker build -t $image .
      - run:
          name: prepare for scan
          command: chmod +x /twistlock/twistcli
      - run:
          name: scan
          command: out=`/twistlock/twistcli images scan -u tw_user -p tw_pass --address $address --vulnerability-threshold $vulnerability --compliance-threshold $compliance --details $image | grep -c FAIL`
      - run:
          name: examin result
          command: if [ $out !=0 ]; then echo "vulnerability or compliance violation detected" && exit 1; else echo "image: "$image" is ready to publish in Dockerhub"; fi;
      - run:
          name: docker login
          command: docker login -u $username -p $password -e $mailaddress     
      - run:
          name: docker push
          command: docker push $image
          
