version: 2
jobs:
  build:
    docker:
      - image: circleci/build-image
    steps:
      - run:
          name: GET Dockerfile 
          command: wget https://raw.githubusercontent.com/minepicco/speechtotext-dockerfile/master/Dockerfile -O Dockerfile
      - run:
          name: build
          command: docker build . --file Dockerfile --tag minepicco/speechtotext:latest


